language: node_js
node_js:
  - "10"
dist: trusty
install:
  - chmod +x ./checker.sh
script:
  - ./checker.sh suka.moe www.suka.moe blog.suka.moe lab.suka.moe cdn.suka.moe theme.suka.moe suka.js.org
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target_branch: gh-pages
  email: $GITHUB_EMAIL
  name: $GITHUB_USER
  on:
    branch: master